// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pdiscovery

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpdiscovery "go.opentelemetry.io/collector/pdata/internal/data/protogen/discovery/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ScopeDiscoverySlice logically represents a slice of ScopeDiscovery.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewScopeDiscoverySlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ScopeDiscoverySlice struct {
	orig *[]*otlpdiscovery.ScopeDiscovery
	state *internal.State
}

func newScopeDiscoverySlice(orig *[]*otlpdiscovery.ScopeDiscovery, state *internal.State) ScopeDiscoverySlice {
	return ScopeDiscoverySlice{orig: orig, state: state}
}

// NewScopeDiscoverySlice creates a ScopeDiscoverySlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewScopeDiscoverySlice() ScopeDiscoverySlice {
	orig := []*otlpdiscovery.ScopeDiscovery(nil)
	state := internal.StateMutable
	return newScopeDiscoverySlice(&orig, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewScopeDiscoverySlice()".
func (es ScopeDiscoverySlice) Len() int {
	return len(*es.orig)
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//   for i := 0; i < es.Len(); i++ {
//       e := es.At(i)
//       ... // Do something with the element
//   }
func (es ScopeDiscoverySlice) At(i int) ScopeDiscovery {
	return newScopeDiscovery((*es.orig)[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ScopeDiscoverySlice can be initialized:
//   es := NewScopeDiscoverySlice()
//   es.EnsureCapacity(4)
//   for i := 0; i < 4; i++ {
//       e := es.AppendEmpty()
//       // Here should set all the values for e.
//   }
func (es ScopeDiscoverySlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(*es.orig)
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpdiscovery.ScopeDiscovery, len(*es.orig), newCap)
	copy(newOrig, *es.orig)
	*es.orig = newOrig
}

// AppendEmpty will append to the end of the slice an empty ScopeDiscovery.
// It returns the newly added ScopeDiscovery.
func (es ScopeDiscoverySlice) AppendEmpty() ScopeDiscovery {
	es.state.AssertMutable()
	*es.orig = append(*es.orig, &otlpdiscovery.ScopeDiscovery{})
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ScopeDiscoverySlice) MoveAndAppendTo(dest ScopeDiscoverySlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if *dest.orig == nil {
		// We can simply move the entire vector and avoid any allocations.
		*dest.orig = *es.orig
	} else {
		*dest.orig = append(*dest.orig, *es.orig...)
	}
	*es.orig = nil
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ScopeDiscoverySlice) RemoveIf(f func(ScopeDiscovery) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(*es.orig); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		(*es.orig)[newLen] = (*es.orig)[i]
		newLen++
	}
	*es.orig = (*es.orig)[:newLen]
}


// CopyTo copies all elements from the current slice overriding the destination.
func (es ScopeDiscoverySlice) CopyTo(dest ScopeDiscoverySlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(*dest.orig)
	if srcLen <= destCap {
		(*dest.orig) = (*dest.orig)[:srcLen:destCap]
		for i := range *es.orig {
			newScopeDiscovery((*es.orig)[i], es.state).CopyTo(newScopeDiscovery((*dest.orig)[i], dest.state))
		}
		return
	}
	origs := make([]otlpdiscovery.ScopeDiscovery, srcLen)
	wrappers := make([]*otlpdiscovery.ScopeDiscovery, srcLen)
	for i := range *es.orig {
		wrappers[i] = &origs[i]
		newScopeDiscovery((*es.orig)[i], es.state).CopyTo(newScopeDiscovery(wrappers[i], dest.state))
	}
	*dest.orig = wrappers
}

// Sort sorts the ScopeDiscovery elements within ScopeDiscoverySlice given the
// provided less function so that two instances of ScopeDiscoverySlice
// can be compared.
func (es ScopeDiscoverySlice) Sort(less func(a, b ScopeDiscovery) bool) {
	es.state.AssertMutable()
	sort.SliceStable(*es.orig, func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
