// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pdiscovery

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpdiscovery "go.opentelemetry.io/collector/pdata/internal/data/protogen/discovery/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceDiscoverySlice logically represents a slice of ResourceDiscovery.
//
// This is a reference type. If passed by value and callee modifies it, the
// caller will see the modification.
//
// Must use NewResourceDiscoverySlice function to create new instances.
// Important: zero-initialized instance is not valid for use.
type ResourceDiscoverySlice struct {
	orig *[]*otlpdiscovery.ResourceDiscovery
	state *internal.State
}

func newResourceDiscoverySlice(orig *[]*otlpdiscovery.ResourceDiscovery, state *internal.State) ResourceDiscoverySlice {
	return ResourceDiscoverySlice{orig: orig, state: state}
}

// NewResourceDiscoverySlice creates a ResourceDiscoverySlice with 0 elements.
// Can use "EnsureCapacity" to initialize with a given capacity.
func NewResourceDiscoverySlice() ResourceDiscoverySlice {
	orig := []*otlpdiscovery.ResourceDiscovery(nil)
	state := internal.StateMutable
	return newResourceDiscoverySlice(&orig, &state)
}

// Len returns the number of elements in the slice.
//
// Returns "0" for a newly instance created with "NewResourceDiscoverySlice()".
func (es ResourceDiscoverySlice) Len() int {
	return len(*es.orig)
}

// At returns the element at the given index.
//
// This function is used mostly for iterating over all the values in the slice:
//   for i := 0; i < es.Len(); i++ {
//       e := es.At(i)
//       ... // Do something with the element
//   }
func (es ResourceDiscoverySlice) At(i int) ResourceDiscovery {
	return newResourceDiscovery((*es.orig)[i], es.state)
}

// EnsureCapacity is an operation that ensures the slice has at least the specified capacity.
// 1. If the newCap <= cap then no change in capacity.
// 2. If the newCap > cap then the slice capacity will be expanded to equal newCap.
//
// Here is how a new ResourceDiscoverySlice can be initialized:
//   es := NewResourceDiscoverySlice()
//   es.EnsureCapacity(4)
//   for i := 0; i < 4; i++ {
//       e := es.AppendEmpty()
//       // Here should set all the values for e.
//   }
func (es ResourceDiscoverySlice) EnsureCapacity(newCap int) {
	es.state.AssertMutable()
	oldCap := cap(*es.orig)
	if newCap <= oldCap {
		return
	}

	newOrig := make([]*otlpdiscovery.ResourceDiscovery, len(*es.orig), newCap)
	copy(newOrig, *es.orig)
	*es.orig = newOrig
}

// AppendEmpty will append to the end of the slice an empty ResourceDiscovery.
// It returns the newly added ResourceDiscovery.
func (es ResourceDiscoverySlice) AppendEmpty() ResourceDiscovery {
	es.state.AssertMutable()
	*es.orig = append(*es.orig, &otlpdiscovery.ResourceDiscovery{})
	return es.At(es.Len() - 1)
}

// MoveAndAppendTo moves all elements from the current slice and appends them to the dest.
// The current slice will be cleared.
func (es ResourceDiscoverySlice) MoveAndAppendTo(dest ResourceDiscoverySlice) {
	es.state.AssertMutable()
	dest.state.AssertMutable()
	if *dest.orig == nil {
		// We can simply move the entire vector and avoid any allocations.
		*dest.orig = *es.orig
	} else {
		*dest.orig = append(*dest.orig, *es.orig...)
	}
	*es.orig = nil
}

// RemoveIf calls f sequentially for each element present in the slice.
// If f returns true, the element is removed from the slice.
func (es ResourceDiscoverySlice) RemoveIf(f func(ResourceDiscovery) bool) {
	es.state.AssertMutable()
	newLen := 0
	for i := 0; i < len(*es.orig); i++ {
		if f(es.At(i)) {
			continue
		}
		if newLen == i {
			// Nothing to move, element is at the right place.
			newLen++
			continue
		}
		(*es.orig)[newLen] = (*es.orig)[i]
		newLen++
	}
	*es.orig = (*es.orig)[:newLen]
}


// CopyTo copies all elements from the current slice overriding the destination.
func (es ResourceDiscoverySlice) CopyTo(dest ResourceDiscoverySlice) {
	dest.state.AssertMutable()
	srcLen := es.Len()
	destCap := cap(*dest.orig)
	if srcLen <= destCap {
		(*dest.orig) = (*dest.orig)[:srcLen:destCap]
		for i := range *es.orig {
			newResourceDiscovery((*es.orig)[i], es.state).CopyTo(newResourceDiscovery((*dest.orig)[i], dest.state))
		}
		return
	}
	origs := make([]otlpdiscovery.ResourceDiscovery, srcLen)
	wrappers := make([]*otlpdiscovery.ResourceDiscovery, srcLen)
	for i := range *es.orig {
		wrappers[i] = &origs[i]
		newResourceDiscovery((*es.orig)[i], es.state).CopyTo(newResourceDiscovery(wrappers[i], dest.state))
	}
	*dest.orig = wrappers
}

// Sort sorts the ResourceDiscovery elements within ResourceDiscoverySlice given the
// provided less function so that two instances of ResourceDiscoverySlice
// can be compared.
func (es ResourceDiscoverySlice) Sort(less func(a, b ResourceDiscovery) bool) {
	es.state.AssertMutable()
	sort.SliceStable(*es.orig, func(i, j int) bool { return less(es.At(i), es.At(j)) })
}
