// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pdiscovery

import (
	"testing"
	"unsafe"

	"github.com/stretchr/testify/assert"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpdiscovery "go.opentelemetry.io/collector/pdata/internal/data/protogen/discovery/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

func TestDiscoveryRecordSlice(t *testing.T) {
	es := NewDiscoveryRecordSlice()
	assert.Equal(t, 0, es.Len())
	state := internal.StateMutable
	es = newDiscoveryRecordSlice(&[]*otlpdiscovery.DiscoveryRecord{}, &state)
	assert.Equal(t, 0, es.Len())

	emptyVal := NewDiscoveryRecord()
	testVal := generateTestDiscoveryRecord()
	for i := 0; i < 7; i++ {
		el := es.AppendEmpty()
		assert.Equal(t, emptyVal, es.At(i))
		fillTestDiscoveryRecord(el)
		assert.Equal(t, testVal, es.At(i))
	}
	assert.Equal(t, 7, es.Len())
}

func TestDiscoveryRecordSliceReadOnly(t *testing.T) {
	sharedState := internal.StateReadOnly
	es := newDiscoveryRecordSlice(&[]*otlpdiscovery.DiscoveryRecord{}, &sharedState)
	assert.Equal(t, 0, es.Len())
	assert.Panics(t, func() { es.AppendEmpty() })
	assert.Panics(t, func() { es.EnsureCapacity(2) })
	es2 := NewDiscoveryRecordSlice()
	es.CopyTo(es2)
	assert.Panics(t, func() { es2.CopyTo(es) })
	assert.Panics(t, func() { es.MoveAndAppendTo(es2) })
	assert.Panics(t, func() { es2.MoveAndAppendTo(es) })
}

func TestDiscoveryRecordSlice_CopyTo(t *testing.T) {
	dest := NewDiscoveryRecordSlice()
	// Test CopyTo to empty
	NewDiscoveryRecordSlice().CopyTo(dest)
	assert.Equal(t, NewDiscoveryRecordSlice(), dest)

	// Test CopyTo larger slice
	generateTestDiscoveryRecordSlice().CopyTo(dest)
	assert.Equal(t, generateTestDiscoveryRecordSlice(), dest)

	// Test CopyTo same size slice
	generateTestDiscoveryRecordSlice().CopyTo(dest)
	assert.Equal(t, generateTestDiscoveryRecordSlice(), dest)
}

func TestDiscoveryRecordSlice_EnsureCapacity(t *testing.T) {
	es := generateTestDiscoveryRecordSlice()

	// Test ensure smaller capacity.
	const ensureSmallLen = 4
	es.EnsureCapacity(ensureSmallLen)
	assert.Less(t, ensureSmallLen, es.Len())
	assert.Equal(t, es.Len(), cap(*es.orig))
	assert.Equal(t, generateTestDiscoveryRecordSlice(), es)

	// Test ensure larger capacity
	const ensureLargeLen = 9
	es.EnsureCapacity(ensureLargeLen)
	assert.Less(t, generateTestDiscoveryRecordSlice().Len(), ensureLargeLen)
	assert.Equal(t, ensureLargeLen, cap(*es.orig))
	assert.Equal(t, generateTestDiscoveryRecordSlice(), es)
}

func TestDiscoveryRecordSlice_MoveAndAppendTo(t *testing.T) {
	// Test MoveAndAppendTo to empty
	expectedSlice := generateTestDiscoveryRecordSlice()
	dest := NewDiscoveryRecordSlice()
	src := generateTestDiscoveryRecordSlice()
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestDiscoveryRecordSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo empty slice
	src.MoveAndAppendTo(dest)
	assert.Equal(t, generateTestDiscoveryRecordSlice(), dest)
	assert.Equal(t, 0, src.Len())
	assert.Equal(t, expectedSlice.Len(), dest.Len())

	// Test MoveAndAppendTo not empty slice
	generateTestDiscoveryRecordSlice().MoveAndAppendTo(dest)
	assert.Equal(t, 2*expectedSlice.Len(), dest.Len())
	for i := 0; i < expectedSlice.Len(); i++ {
		assert.Equal(t, expectedSlice.At(i), dest.At(i))
		assert.Equal(t, expectedSlice.At(i), dest.At(i+expectedSlice.Len()))
	}
}

func TestDiscoveryRecordSlice_RemoveIf(t *testing.T) {
	// Test RemoveIf on empty slice
	emptySlice := NewDiscoveryRecordSlice()
	emptySlice.RemoveIf(func(el DiscoveryRecord) bool {
		t.Fail()
		return false
	})

	// Test RemoveIf
	filtered := generateTestDiscoveryRecordSlice()
	pos := 0
	filtered.RemoveIf(func(el DiscoveryRecord) bool {
		pos++
		return pos%3 == 0
	})
	assert.Equal(t, 5, filtered.Len())
}

func TestDiscoveryRecordSlice_Sort(t *testing.T) {
	es := generateTestDiscoveryRecordSlice()
	es.Sort(func(a, b DiscoveryRecord) bool {
		return uintptr(unsafe.Pointer(a.orig)) < uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.True(t, uintptr(unsafe.Pointer(es.At(i-1).orig)) < uintptr(unsafe.Pointer(es.At(i).orig)))
	}
	es.Sort(func(a, b DiscoveryRecord) bool {
		return uintptr(unsafe.Pointer(a.orig)) > uintptr(unsafe.Pointer(b.orig))
	})
	for i := 1; i < es.Len(); i++ {
		assert.True(t, uintptr(unsafe.Pointer(es.At(i-1).orig)) > uintptr(unsafe.Pointer(es.At(i).orig)))
	}
}

func generateTestDiscoveryRecordSlice() DiscoveryRecordSlice {
	es := NewDiscoveryRecordSlice()
	fillTestDiscoveryRecordSlice(es)
	return es
}

func fillTestDiscoveryRecordSlice(es DiscoveryRecordSlice) {
	*es.orig = make([]*otlpdiscovery.DiscoveryRecord, 7)
	for i := 0; i < 7; i++ {
		(*es.orig)[i] = &otlpdiscovery.DiscoveryRecord{}
		fillTestDiscoveryRecord(newDiscoveryRecord((*es.orig)[i], es.state))
	}
}