// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by "pdata/internal/cmd/pdatagen/main.go". DO NOT EDIT.
// To regenerate this file run "make genpdata".

package pdiscovery

import (
	"sort"

	"go.opentelemetry.io/collector/pdata/internal"
	"go.opentelemetry.io/collector/pdata/internal/data"
	otlpdiscovery "go.opentelemetry.io/collector/pdata/internal/data/protogen/discovery/v1"
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// DiscoveryRecord are experimental implementation of OpenTelemetry Discovery Data Model.

//
// This is a reference type, if passed by value and callee modifies it the
// caller will see the modification.
//
// Must use NewDiscoveryRecord function to create new instances.
// Important: zero-initialized instance is not valid for use.
type DiscoveryRecord struct {
	orig *otlpdiscovery.DiscoveryRecord
	state *internal.State
}

func newDiscoveryRecord(orig *otlpdiscovery.DiscoveryRecord, state *internal.State) DiscoveryRecord {
	return DiscoveryRecord{orig: orig, state: state}
}

// NewDiscoveryRecord creates a new empty DiscoveryRecord.
//
// This must be used only in testing code. Users should use "AppendEmpty" when part of a Slice,
// OR directly access the member if this is embedded in another struct.
func NewDiscoveryRecord() DiscoveryRecord {
	state := internal.StateMutable
	return newDiscoveryRecord(&otlpdiscovery.DiscoveryRecord{}, &state)
}

// MoveTo moves all properties from the current struct overriding the destination and
// resetting the current instance to its zero value
func (ms DiscoveryRecord) MoveTo(dest DiscoveryRecord) {
	ms.state.AssertMutable()
	dest.state.AssertMutable()
	*dest.orig = *ms.orig
	*ms.orig = otlpdiscovery.DiscoveryRecord{}
}



// Resource returns the resource associated with this DiscoveryRecord.
func (ms DiscoveryRecord) Resource() pcommon.Resource {
	return pcommon.Resource(internal.NewResource(&ms.orig.Resource, ms.state))
}


// CopyTo copies all properties from the current struct overriding the destination.
func (ms DiscoveryRecord) CopyTo(dest DiscoveryRecord) {
	dest.state.AssertMutable()
		ms.Resource().CopyTo(dest.Resource())
}
